### ISSUE TITLE
NullPointerException whilst attempting to fit the dataSetIterator into the multiLayerNetwork

### ISSUE THREAD

**Issue by KeironO** [bio-ontology-research-group/neural-network-plant-trait-classification#1]
The following configuration is throwing up a `NullPointerException`

```
        RecordReader recordReader = new ImageRecordReader(numInputRows, numInputCols, true);
        recordReader.initialize(new FileSplit(new File(labeledPath)));
        DataSetIterator dataSetIterator = new RecordReaderDataSetIterator(recordReader, numImages, numInput, labels.size());
```

I have looked at the jdb, and the image data is loading without any obvious issue. This error arrises regardless of what `MultiLayerConfiguration` is being used.

Stack trace below:

```
Exception in thread "main" java.lang.NullPointerException
    at org.deeplearning4j.nn.layers.feedforward.rbm.RBM.computeGradientAndScore(RBM.java:164)
    at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:114)
    at org.deeplearning4j.optimize.solvers.BaseOptimizer.optimize(BaseOptimizer.java:131)
    at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
    at org.deeplearning4j.nn.layers.BaseLayer.fit(BaseLayer.java:493)
    at org.deeplearning4j.nn.layers.feedforward.rbm.RBM.fit(RBM.java:395)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.pretrain(MultiLayerNetwork.java:165)
    at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1030)
    at org.deeplearning4j.Project.FloweringAndNotFloweringSmallScale.main(FloweringAndNotFloweringSmallScale.java:88)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by KeironO** [comment]
Fixed. The API for DL4J has changed a little, and it's now imperative to include specific parameters within the `MultiLayerConfiguration`

**Comment by MiguelAngelRG** [comment]
Great!!!!!… so you have been finished everything?….

Congratulation!!!! :D

Miguel Angel
